version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crud_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: node_backend
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    working_dir: /app
    command: ["npm", "run", "dev"]
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=crud_db
      - DB_DIALECT=postgres

volumes:
  postgres_data:
